### ISSUE TITLE
Update repo

### ISSUE THREAD

**Issue by harshasrikara** [acmutd/htf-trackit#1]
**Overview**
Given the new use of this repo to store information / TrackIT data for ACM Education workshops and other content, update the repo to be friendly to new users wanting to add to it

**Task List**
 - [ ] Organize files / folders to match `/{workshop-name}/markdown/{slide-number}`
 - [ ] Organize generated html to match `/{workshop-name}/html/{slide-number}`
 - [ ] Update readme with the standard acm template readme format
 - [ ] Include clear information on how to use this repository & link it to the TrackIT repo
 - [ ] Provide examples of using the `iframe` with html snippets from this repo

**Comment by WillieCubed** [comment]
Closing since this issue is stale and since the event is long since passed.
